### ISSUE TITLE
PipeMethodCalls.PipeInvokeFailedException

### ISSUE THREAD

**Issue by Thazin22** [gerardo-lijs/CrystalReportsRunner.Samples#2]
When I run SampleCaller, instruciton await engine.ShowReport(report) got errors.
Detail Error >>
PipeMethodCalls.PipeInvokeFailedException: 'System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'CrystalDecisions.ReportAppServer.CommLayer...

**Comment by gerardo-lijs** [comment]
Hi, the samples reference v13.0.32 x64 of Crystal Reports. Make sure Crystal Reports runtime v13.0.32 x64 is installed in your computer or if you're using a different version change the referenced NuGet package.
