### ISSUE TITLE
Hi, i try yo ur sample project but i get an error. I put an image down side.

### ISSUE THREAD

**Issue by tanselkonuk** [gerardo-lijs/CrystalReportsRunner.Samples#4]
![image](https://github.com/gerardo-lijs/CrystalReportsRunner.Samples/assets/71979781/caefcb81-5c66-42b7-8c23-dc0363d7a3ef)

**Comment by gerardo-lijs** [comment]
Hi,
This samples are using LijsDev.CrystalReportsRunner.13.0.34.x64. Can you please check that you have installed Crystal Reports Runtime for that specific version and platform?
![image](https://github.com/gerardo-lijs/CrystalReportsRunner.Samples/assets/14139570/102c32ab-efd1-4044-917e-c2dd20162d34)
