### ISSUE TITLE
.rpt is different in SampleCaller

### ISSUE THREAD

**Issue by enricoroselino** [gerardo-lijs/CrystalReportsRunner.Samples#8]
Hello, your  package is amazingly run in .NET 8. But why your .rpt doesn't have .cs ?  i made a new .rpt but it bundled with the .cs and regenerated if i delete it. 

can you tell me how to make the .rpt like yours ? thank you in advance.

![image](https://github.com/user-attachments/assets/dfddd009-0cef-4d2c-b8a4-049327040163)

**Comment by enricoroselino** [comment]
![image](https://github.com/user-attachments/assets/3f81c340-43c6-46ea-b0eb-59b7bf062c5e)

okay i deleted the custom tool code generation, but still wonder if there is any item template for .rpt w/o the code gen

**Comment by gerardo-lijs** [comment]
Hi, to create reports we use the paid version of Crystal Reports 2020, which is a standalone program. This creates just an RPT file. I don't have experience creating from Visual Studio editor (free version) which is the one it seems you are using.
